"""Build Data/raw_assets.md from _cache/records.jsonl and _cache/signs.json. usage: make_manifest.py <raw_assets dir>"""
import sys,os,json
raw=sys.argv[1]
recs=[json.loads(l) for l in open(os.path.join(raw,'_cache','records.jsonl'))]
USE={}
def u(text,*ids):
    for i in ids: USE[i]=text
u('Road: fresh dark asphalt (new surface)','asphalt_track','asphalt_pit_lane')
u('Road: worn/old light-grey asphalt (typical German side road)','asphalt_04','asphalt_01','Asphalt031')
u('Road: patched/cracked asphalt','asphalt_02','aerial_asphalt_01')
u('Road: dark grey asphalt','Asphalt015')
u('Road: Kopfsteinpflaster (cobblestone setts), 4K','cobblestone_floor_08','cobblestone_floor_02','PavingStones070')
u('Sidewalk/yard: cobblestone / small setts','cobblestone_03','cobblestone_floor_09','PavingStones115A')
u('Sidewalk: red/brown interlocking/rectangular concrete pavers','brick_pavement','brick_floor_003','concrete_pavers_02','PavingStones092')
u('Sidewalk: grey concrete pavers / Gehwegplatten','concrete_pavers','concrete_pavement','concrete_pavement_02','brick_pavement_03','large_square_pattern_01')
u('Curb stone / granite slabs (closest match; no dedicated curb texture exists)','granite_tile_04')
u('Ground: grass / lawn','leafy_grass','grass_ground','Ground037')
u('Ground: meadow / forest-edge grass-dirt mix','forrest_ground_01')
u('Ground: gravel','gravel_floor_02','gravel_road','gravel_ground_01','Ground032')
u('Ground: dirt track / field soil','farm_soil','dry_mud_field_001','dirt_floor','Ground066','Ground048')
u('Ground: forest floor','forest_ground_05','forest_leaves_04','Ground038')
u('Facade: red/brown Klinker brick','brick_wall_001','brick_wall_006','brick_4','brick_wall_09','exterior_wall_cladding_02','brick_wall_10')
u('Facade: white/beige plaster-render','white_stucco','white_stucco_02','beige_wall_001','beige_wall_002','plastered_wall','white_plaster_02')
u('Facade: concrete','concrete_wall_001','concrete_wall_004','concrete_slab_wall')
u('Roof: red clay tiles','clay_roof_tiles','clay_roof_tiles_02','clay_roof_tiles_03','roof_tiles')
u('Roof: grey slate/tiles','roof_slates_02','grey_roof_tiles')
u('Misc: corrugated metal (sheds, fences)','corrugated_iron','corrugated_iron_02','rusty_corrugated_iron')
u('Misc: wood planks (fences, sheds, decks)','wood_planks','wood_planks_grey','wood_floor_deck')
for i in range(3,12): USE[f'ManholeCover{i:03d}']='Road decal: manhole/drain cover (photogrammetry, has opacity map)'
for h,t in [('binnenalster','Overcast day HDRI (Hamburg Binnenalster)'),('hausdorf_meadow','Overcast day HDRI (German meadow)'),('suburban_field_01','Overcast day HDRI (2K, spare)'),
 ('hausdorf_clear_sky','Clear day HDRI (German countryside)'),('hamburg_canal','Clear/golden-hour urban HDRI (Hamburg canal)'),('evening_road_01','Dusk HDRI (road)'),('narrow_moonlit_road','Night HDRI (moonlit road)')]: USE[h]=t
cats=[('Textures - Poly Haven','tex','polyhaven'),('Textures - ambientCG','tex','ambientcg'),('Decals - ambientCG','dec','ambientcg'),('HDRIs','hdri','polyhaven'),('Models (glTF, 2K textures)','model','polyhaven')]
def rel(p): return os.path.relpath(p,raw)
def sz(b): return f"{b/1e6:.0f} MB"
L=["# Raw assets manifest","","Generated by Tools/asset_fetch/make_manifest.py. All assets CC0 unless noted (signs: public domain).","",
"Conventions: Poly Haven textures = `*_diff_*.jpg`, `*_nor_dx_*.png` (DirectX normal, Unreal-ready), `*_rough_*.jpg`, `*_ao_*.jpg`, `*_disp_*.png` (16-bit displacement), `*_metal_*.jpg` where relevant.",
"ambientCG textures = `*_Color`, `*_NormalDX` (DirectX), `*_Roughness`, `*_AmbientOcclusion`, `*_Displacement`; JPG for 2K sets (8-bit displacement), PNG for 4K sets (16-bit displacement). The extra `<AssetId>.png` is a preview image.",
"All materials are photo-based (photogrammetry/photo-scan). Procedural ambientCG materials were deliberately excluded.",""]
tot=0
for title,kind,src in cats:
    rs=[r for r in recs if r['source']==src and (r['kind']==kind or (kind=='dec' and r['id'].startswith('Manhole')))]
    if kind=='tex': rs=[r for r in rs if not r['id'].startswith('Manhole')]
    if not rs: continue
    L+=[f"## {title} ({len(rs)})","","| Local path | Source URL | License | Res | Intended use | Notes |","|---|---|---|---|---|---|"]
    for r in sorted(rs,key=lambda r:(USE.get(r['id'],''),r['id'])):
        notes=[]
        if r['missing']: notes.append('NO '+'/'.join(r['missing']))
        if r.get('normal','').startswith('OpenGL'): notes.append(r['normal'])
        if r.get('method') and r['method']!='PBRPhotogrammetry': notes.append(r['method'])
        if r['kind']=='model': notes.append('files: .gltf + .bin + textures/ (diff, nor_gl, arm=AO/Rough/Metal packed)')
        use=USE.get(r['id']) or ', '.join(r.get('categories',[]))
        L.append(f"| `{rel(r['path'])}/` | {r['url']} | {r['license']} | {r['res']} | {use} | {'; '.join(notes)} ({sz(r['bytes'])}) |")
        tot+=r['bytes']
    L.append('')
sj=os.path.join(raw,'_cache','signs.json')
if os.path.exists(sj):
    s=json.load(open(sj))
    L+=[f"## German StVO traffic signs - Wikimedia Commons SVG ({len(s['recs'])})","",
    "Official StVO sign graphics, tagged Public domain on Commons (amtliche Werke). `signs/svg/Zeichen_<code>.svg`; PNG renders (1024 px tall) in `signs/png/` where available. Edition year is in the Commons title (StVO 1970/1992/2013/2017) - the newest available SVG for each code was chosen; 1970-era files may differ slightly from current signs.","",
    "| File | Commons page | License | Commons title |","|---|---|---|---|"]
    for r in s['recs']: L.append(f"| `signs/svg/{r['file']}` | {(r['page'] if r['page'].startswith('http') else 'https://commons.wikimedia.org/wiki/'+r['page'])} | {r['license']} | {r['title'][5:]} |")
    L+=['',f"Codes with no matching SVG on Commons: {', '.join(s['notfound']) or 'none'}",'']
for t in ['signs/svg','signs/png']:
    pass
L+=['## Notes / gaps','',
'- No car: Poly Haven has only `covered_car` (a tarp-covered car prop, not a drivable/interior model), `old_tyre`, `rusted_wheel_rim_*`; ambientCG has no 3D models at all. No CC0 car with interior exists on these sources.',
'- No window/facade-with-windows texture exists as a photo-scan on Poly Haven/ambientCG (ambientCG Facade/Window materials are procedural, so were skipped). Use `modular_urban_apartments_facade` (model) or build windows from geometry.',
'- No dedicated kerb/curb texture; `granite_tile_04` is the closest. No bollards/traffic-sign poles in Poly Haven models.',
'- ambientCG `RoadLines*` decals are procedural and were skipped; only photogrammetry ManholeCover decals taken.',
'- Procedural ambientCG materials (Grass00x, Facade, Road, Roofing Tiles etc.) skipped because the project requires photoreal photo-based scans.',
'- Not CC0: nothing. All Poly Haven/ambientCG items are CC0. Signs are tagged Public domain on Commons (no attribution required).',
'- beige_wall_002 is a 2048x512 strip and only ships an OpenGL normal map (flip green for Unreal).',
'']
L.append(f"_Total of tracked texture/HDRI/model downloads: {tot/1e9:.2f} GB (excluding signs)_")
open(os.path.join(os.path.dirname(os.path.abspath(__file__)),'..','..','Data','raw_assets.md'),'w').write('\n'.join(L)+'\n')
print('ok',tot/1e9)
