"""Prompts for the advertising posters in the bus shelters (#102), generated by Codex's image tool.

Every brand is fictional and every text is German, so nothing on a poster is a real trademark or a real person. The
posters are CityLight format (1160 by 1710 mm visible); keep headlines short, since only those read from a car.
"""

FORMAT = ("A portrait advertising poster for a back-lit bus shelter case in Hamburg, aspect ratio 1:1.47, "
          "photorealistic, professional print design, all text in German and spelled exactly as given, "
          "no real brands, logos or famous people, no web addresses.")

ADS = {
    "supermarket": (
        "A weekly offer from the fictional supermarket chain MARKTKORB (green and red wordmark). Headline "
        "'WOCHENANGEBOT', subline 'Erdbeeren aus den Vierlanden', a large price '1,99 €' with '500 g', a photo of fresh "
        "strawberries in a cardboard punnet on a wooden market table."
    ),
    "culture": (
        "A theatre poster for a fictional musical: the title 'Die Elbsirene' in large letters and under it the subtitle "
        "'Das Musical', with no dash anywhere, at the fictional 'Theater am Hafen'. "
        "A singer in a flowing dress on a stage lit in deep blue and teal, harbour cranes and water in the background "
        "as stage set, elegant serif title, the line 'Ab 14. November' and small text 'Tickets an allen "
        "Vorverkaufsstellen'."
    ),
    "bank": (
        "An advert for the fictional bank 'Alsterbank' (navy blue wordmark with a small wave symbol). A young couple "
        "laughing with a set of house keys in front of a red-brick Hamburg terraced house, headline 'Ihr Zuhause "
        "beginnt mit einem Gespräch.', small line 'Baufinanzierung von der Alsterbank'."
    ),
    "boogle": (
        "An advert for 'Boogle Maps' by the fictional tech company Boogle, whose wordmark 'Boogle' is set in a clean "
        "rounded sans with each letter in a different bright colour (blue, red, yellow, blue, green, red). A hand "
        "holding a smartphone that shows a map of Hamburg with a bus route, headline 'Schneller ans Ziel. Auch mit dem "
        "Bus.', light minimal white design."
    ),
    "bus_drivers": (
        "A recruiting poster of the fictional public transport company 'Hamburger Busbetriebe' (red wordmark). A "
        "smiling bus driver in uniform at the wheel of a modern red city bus, seen through the windscreen, huge "
        "headline 'Wir suchen Busfahrer:innen.', subline 'Steig ein. Jetzt bewerben.', bold red and white design."
    ),
}
